version: "3.9"

services:
  homewg:
    build: .
    image: YOUR_DOCKERHUB/home-wg-server:latest
    network_mode: host
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun
    environment:
      - DUCKDNS_DOMAIN=denvpn
      - DUCKDNS_TOKEN=${DUCKDNS_TOKEN}
      # optional:
      # - LAN_IFACE=eth0
    volumes:
      - ./configs:/etc/home-wg
    restart: unless-stopped
